	export HADOOP_PREFIX=/bdapps/hadoop
	export PATH=$PATH:${HADOOP_PREFIX}/bin:${HADOOP_PREFIX}/sbin
	export  HADOOP_YARN_HOME=${HADOOP_PREFIX}
	export  HADOOP_MAPPERD_HOME=${HADOOP_PREFIX}
	export  HADOOP_COMMON_HOME=${HADOOP_PREFIX}
	export  HADOOP_HDFS_HOME=${HADOOP_PREFIX}

